name: Run main.py on daily-runner Branch for upload article to db

on:
  schedule:
    - cron: "*/1 * * * *"  # 월~금, UTC 기준 오전 0시 (KST로 오전 9시)
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: daily-runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Set up environment variables
        env:
          NEWS_API_KEY: ${{ secrets.NEWSAPI }}
          OPENAI_API_KEY: ${{ secrets.OPENAIAPI }}
        run: echo "Environment variables are set."

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
        
      # - name: 
      - name: Check directory
        run: |
          ls -al
          cat src/main.py